export const sample_foods = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 10,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '2',
      name: 'Meatball',
      price: 20,
      cookTime: '20-30',
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 5,
      imageUrl: 'food-2.jpg',
      tags: ['SlowFood', 'Lunch'],
    },
    {
      id: '3',
      name: 'Hamburger',
      price: 5,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'food-3.jpg',
      tags: ['FastFood', 'Hamburger'],
    },
    {
      id: '4',
      name: 'Fried Potatoes',
      price: 2,
      cookTime: '15-20',
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 3,
      imageUrl: 'food-4.jpg',
      tags: ['FastFood', 'Fry'],
    },
    {
      id: '5',
      name: 'Chicken Soup',
      price: 11,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: 'food-5.jpg',
      tags: ['SlowFood', 'Soup'],
    },
    {
      id: '6',
      name: 'Vegetables Pizza',
      price: 9,
      cookTime: '40-50',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'food-6.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },

    {
      id: '1008',
      name: 'Carbonara',
      cookTime: '20-30',
      price: 19.00,
      favorite: false,
      origins: ['italy'],
      stars: 4.2,
      imageUrl: 'food-1008.jpg',
      tags: ['SlowFood', 'Pasta', 'Dinner'],
    },
    {
      id: '1009',
      name: 'Fettuccine Alfredo',
      cookTime: '20-30',
      price: 21.00,
      favorite: true,
      origins: ['italy'],
      stars: 4.3,
      imageUrl: 'food-1009.jpg',
      tags: ['SlowFood', 'Pasta', 'Dinner'],
    },
    {
      id: '1010',
      name: 'Chicken Parmesan',
      cookTime: '25-35',
      price: 23.00,
      favorite: true,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'food-1010.jpg',
      tags: ['SlowFood', 'Chicken', 'Dinner'],
    },
    {
      id: '1011',
      name: 'Caesar Salad',
      cookTime: '10-15',
      price: 15.00,
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'food-1011.jpg',
      tags: ['Appetizer', 'Salad', 'Lunch'],
    },
    {
      id: '1012',
      name: 'Cheeseburger',
      cookTime: '10-15',
      price: 18.00,
      favorite: true,
      origins: ['us'],
      stars: 4.3,
      imageUrl: 'food-1012.jpg',
      tags: ['FastFood', 'Burger', 'Lunch'],
    },
    {
      id: '1013',
      name: 'Veggie Burger',
      cookTime: '10-15',
      price: 17.00,
      favorite: false,
      origins: ['us'],
      stars: 4.1,
      imageUrl: 'food-1013.jpg',
      tags: ['FastFood', 'Burger', 'Lunch'],
    },
    {
      id: '1014',
      name: 'Belgian Waffle',
      cookTime: '10-20',
      price: 12.00,
      favorite: true,
      origins: ['belgium'],
      stars: 4.4,
      imageUrl: 'food-1014.jpg',
      tags: ['Breakfast', 'Sweet'],
    },
    {
      id: '1015',
      name: 'Eggs Benedict',
      cookTime: '15-25',
      price: 14.00,
      favorite: false,
      origins: ['us'],
      stars: 4.2,
      imageUrl: 'food-1015.jpg',
      tags: ['Breakfast', 'Eggs'],
    },
    {
      id: '1016',
      name: 'Chicken Shawarma',
      cookTime: '20-30',
      price: 22.00,
      favorite: true,
      origins: ['middle east'],
      stars: 4.5,
      imageUrl: 'food-1016.jpg',
      tags: ['FastFood', 'Wrap', 'Lunch'],
    },
    {
      id: '1017',
      name: 'Falafel Wrap',
      cookTime: '15-25',
      price: 19.00,
      favorite: false,
      origins: ['middle east'],
      stars: 4.0,
      imageUrl: 'food-1017.jpg',
      tags: ['FastFood', 'Wrap', 'Lunch'],
    },
    {
      id: '1018',
      name: 'Chocolate Brownie',
      cookTime: '20-30',
      price: 8.00,
      favorite: true,
      origins: ['us'],
      stars: 4.7,
      imageUrl: 'food-1018.jpg',
      tags: ['Dessert', 'Chocolate'],
    },
    {
      id: '1019',
      name: 'Tiramisu',
      cookTime: '20-30',
      price: 10.00,
      favorite: true,
      origins: ['italy'],
      stars: 4.8,
      imageUrl: 'food-1019.jpg',
      tags: ['Dessert', 'Sweet'],
    },
    {
      id: '1020',
      name: 'Iced Caramel Macchiato',
      cookTime: '5-10',
      price: 6.00,
      favorite: false,
      origins: ['us'],
      stars: 4.3,
      imageUrl: 'food-1020.jpg',
      tags: ['ColdDrink', 'Coffee'],
    },
    {
      id: '1021',
      name: 'Iced Lemonade',
      cookTime: '5-10',
      price: 5.00,
      favorite: true,
      origins: ['us'],
      stars: 4.1,
      imageUrl: 'food-1021.jpg',
      tags: ['ColdDrink', 'Lemon'],
    },
    {
      id: '1022',
      name: 'Hot Chocolate',
      cookTime: '5-10',
      price: 4.00,
      favorite: true,
      origins: ['us'],
      stars: 4.5,
      imageUrl: 'food-1022.jpg',
      tags: ['HotDrink', 'Chocolate'],
    },
    {
      id: '1023',
      name: 'Cappuccino',
      cookTime: '5-10',
      price: 4.00,
      favorite: false,
      origins: ['italy'],
      stars: 4.3,
      imageUrl: 'food-1023.jpg',
      tags: ['HotDrink', 'Coffee'],
    },
    {
      id: '1024',
      name: 'Virgin Mojito',
      cookTime: '5-10',
      price: 7.00,
      favorite: false,
      origins: ['cuba'],
      stars: 4.2,
      imageUrl: 'food-1024.jpg',
      tags: ['Cocktail', 'NonAlcoholic'],
    },
    {
      id: '1025',
      name: 'Piña Colada',
      cookTime: '5-10',
      price: 80.00,
      favorite: true,
      origins: ['puerto rico'],
      stars: 4.5,
      imageUrl: 'food-1025.jpg',
      tags: ['Cocktail', 'NonAlcoholic'],
    },
  ];
  
  export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
  ];
  
  export const sample_users = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john@gmail.com',
      password: '12345',
      address: 'Toronto On',
      isAdmin: false,
    },
    {
      id: 2,
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '12345',
      address: 'Shanghai',
      isAdmin: true,
    },
  ];